monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        mail:
            type: fingers_crossed
            action_level: error
            handler: duplicado

        duplicado:
            type: deduplication
            handler: swift

        swift:
            type: swift_mailer
            from_email: 'error@email.com'
            to_email: 'envioson@gmail.com'
            subject: 'Ocorreu algum erro: %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html

        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
